# Generated by Django 5.2.4 on 2025-08-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memo',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': '메모', 'verbose_name_plural': '메모들'},
        ),
        migrations.AddField(
            model_name='memo',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='상단 고정'),
        ),
        migrations.AddField(
            model_name='memo',
            name='priority',
            field=models.CharField(choices=[('low', '낮음'), ('normal', '보통'), ('high', '높음'), ('urgent', '긴급')], default='normal', max_length=10, verbose_name='중요도'),
        ),
    ]
